version: '3.3'

services:
  globo-aplausos-backend:
    build: .
    container_name: globo-aplausos-backend
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    networks:
      - globo_aplausos
    env_file:
      - .env

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./database/dumps:/data/db
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    networks:
      - globo_aplausos
    env_file:
      - .env

networks:
  globo_aplausos:
    driver: bridge
