#!/bin/sh
current_branch=$(git symbolic-ref --short HEAD)

if [[ "$current_branch" =~ ^(feature|fix)/US-[0-9]+ ]] || [[ "$current_branch" =~ ^(feature|fix)/NOUS ]]; then
    echo "Nome da branch de acordo com o formato: 'feature/US-Número-descrição' ou 'fix/US-Número-descrição' ou 'feature/NOUS' ou 'fix/NOUS' - Push realizado com sucesso"
    exit 0
else
    echo "Erro - Nome da branch não está de acordo com o formato solicitado: 'feature/US-Número-descrição' ou 'fix/US-Número-descrição' ou 'feature/NOUS' ou 'fix/NOUS'"
    exit 1
fi